'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmDashboard

    '''<summary>
    '''ltrParticipantesComite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrParticipantesComite As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrParticipantesTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrParticipantesTipo As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrActividadesPorComite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrActividadesPorComite As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrComiteSatisfaccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrComiteSatisfaccion As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrActividadesPorTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrActividadesPorTipo As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrPersonal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrPersonal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrParticipantes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrParticipantes As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrTasaCrecimiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrTasaCrecimiento As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrUltimoAnio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrUltimoAnio As Global.System.Web.UI.WebControls.Literal
End Class
