'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmSatisfaccionPorComite

    '''<summary>
    '''ltrComite1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrComite1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrComite2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrComite2 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrComite3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrComite3 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrComite4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrComite4 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrComite5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrComite5 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrComite6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrComite6 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrComite7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrComite7 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrComite8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrComite8 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrComite9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrComite9 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrComite10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrComite10 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrComite11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrComite11 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrComite12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrComite12 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrComite13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrComite13 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrComite14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrComite14 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrComite15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrComite15 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrComite16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrComite16 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrComite17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrComite17 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrComite18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrComite18 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrComite19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrComite19 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrComite20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrComite20 As Global.System.Web.UI.WebControls.Literal
End Class
