'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmCronogramaActividades

    '''<summary>
    '''imgSectionTitleImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSectionTitleImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''calActividades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calActividades As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''lbtnToday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnToday As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnThisWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnThisWeek As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnThisMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnThisMonth As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hdnStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnStartDate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnEndDate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''upnlEvents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlEvents As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblTitleTabCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitleTabCalendar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptCalendarioActividades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptCalendarioActividades As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''tblMsgNoActividades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblMsgNoActividades As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblNoActividades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoActividades As Global.System.Web.UI.WebControls.Label
End Class
