'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmCronogramaActividades

    '''<summary>
    '''calActividades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calActividades As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''lbtnHoy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnHoy As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnEstaSemana control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnEstaSemana As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnEsteMes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnEsteMes As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hdnFechaInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnFechaInicio As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnFechaFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnFechaFin As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''upnlActividades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlActividades As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblTituloCalendario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloCalendario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptCalendarioActividades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptCalendarioActividades As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''tblMsgNoActividades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblMsgNoActividades As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblNoActividades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoActividades As Global.System.Web.UI.WebControls.Label
End Class
