'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmDetalleActividad

    '''<summary>
    '''hdnCompanyID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCompanyID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblTitleEvent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitleEvent As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDateEvent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateEvent As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHourEvent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHourEvent As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAddressEvent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddressEvent As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDescriptionEvent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescriptionEvent As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RegisterNow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegisterNow As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''ibtnRegresar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnRegresar As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnRegisterNow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnRegisterNow As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblRegistrationClosed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegistrationClosed As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tdMessageEndDateEvent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdMessageEndDateEvent As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lblMessageEndDateEvent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessageEndDateEvent As Global.System.Web.UI.WebControls.Label
End Class
